name: ledgerly
description: "A modern Flutter expense tracker powered by Google Sheets"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.7"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0

  # State management + hooks
  hooks_riverpod: ^2.5.1

  # Networking
  dio: ^5.5.0

  # Environment variables
  flutter_dotenv: ^5.2.0

  # Charts
  fl_chart: ^0.70.0

  # Animations
  flutter_animate: ^4.5.0

  # SVG icons
  flutter_svg: ^2.0.12

  # Local storage (theme toggle later)
  shared_preferences: ^2.2.3

  # App Launcher
  url_launcher: ^6.2.6

  appcheck: ^1.7.0

  flutter_device_apps: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env.dev
    - .env.prod
